name: Newman Run

on:
  pull_request:
    branches:
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: datumchallenge.postman_collection.json
          environment: datumchallenge.postman_globals
          
      - name: Run Collection
        run:  newman run datumchallenge.postman_collection.json -e datumchallenge.postman_globals
